<?php
/**
 * @file
 * os2web_contact.panels_default.inc
 */

/**
 * Implements hook_default_panels_mini().
 */
function os2web_contact_default_panels_mini() {
  $export = array();

  $mini = new stdClass();
  $mini->disabled = FALSE; /* Edit this to true to make a default mini disabled initially */
  $mini->api_version = 1;
  $mini->name = 'os2web_contact_panel_sidebar';
  $mini->category = 'OS2Web';
  $mini->admin_title = 'Højre blokke generel';
  $mini->admin_description = 'Højre blokke på f.eks. Nyheder - inkluderer valgfri spotbokse. ';
  $mini->requiredcontexts = array();
  $mini->contexts = array();
  $mini->relationships = array();
  $display = new panels_display();
  $display->layout = 'onecol';
  $display->layout_settings = array();
  $display->panel_settings = array(
    'style_settings' => array(
      'default' => NULL,
      'middle' => NULL,
    ),
  );
  $display->cache = array();
  $display->title = '';
  $display->uuid = '096e6eca-2fa4-4ce5-8937-aff599fb3daa';
  $display->storage_type = 'panels_mini';
  $display->storage_id = 'os2web_contact_panel_sidebar';
  $display->content = array();
  $display->panels = array();
  $pane = new stdClass();
  $pane->pid = 'new-f6d5abe9-3d6b-4125-bd0d-baba12924978';
  $pane->panel = 'middle';
  $pane->type = 'views_panes';
  $pane->subtype = 'os2web_contact_view_contact-panel_pane_1';
  $pane->shown = FALSE;
  $pane->access = array();
  $pane->configuration = array(
    'arguments' => array(
      'nid' => '',
    ),
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = 'f6d5abe9-3d6b-4125-bd0d-baba12924978';
  $display->content['new-f6d5abe9-3d6b-4125-bd0d-baba12924978'] = $pane;
  $display->panels['middle'][0] = 'new-f6d5abe9-3d6b-4125-bd0d-baba12924978';
  $pane = new stdClass();
  $pane->pid = 'new-3fb1383c-5885-42d9-9523-030b0024be8f';
  $pane->panel = 'middle';
  $pane->type = 'views';
  $pane->subtype = 'os2web_contact_view_contact';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'override_pager_settings' => 0,
    'use_pager' => 0,
    'nodes_per_page' => '1',
    'pager_id' => '0',
    'offset' => '0',
    'more_link' => 0,
    'feed_icons' => 0,
    'panel_args' => 0,
    'link_to_view' => 0,
    'args' => '290807',
    'url' => '',
    'display' => 'block',
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 1;
  $pane->locks = array();
  $pane->uuid = '3fb1383c-5885-42d9-9523-030b0024be8f';
  $display->content['new-3fb1383c-5885-42d9-9523-030b0024be8f'] = $pane;
  $display->panels['middle'][1] = 'new-3fb1383c-5885-42d9-9523-030b0024be8f';
  $pane = new stdClass();
  $pane->pid = 'new-03bd8868-b913-4fb9-bce1-009a1000530b';
  $pane->panel = 'middle';
  $pane->type = 'views';
  $pane->subtype = 'os2web_spotbox_view_spot';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'override_pager_settings' => 0,
    'use_pager' => 0,
    'nodes_per_page' => '0',
    'pager_id' => '0',
    'offset' => '0',
    'more_link' => 0,
    'feed_icons' => 0,
    'panel_args' => 0,
    'link_to_view' => 0,
    'args' => '',
    'url' => '',
    'display' => 'block_1',
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 2;
  $pane->locks = array();
  $pane->uuid = '03bd8868-b913-4fb9-bce1-009a1000530b';
  $display->content['new-03bd8868-b913-4fb9-bce1-009a1000530b'] = $pane;
  $display->panels['middle'][2] = 'new-03bd8868-b913-4fb9-bce1-009a1000530b';
  $pane = new stdClass();
  $pane->pid = 'new-65e6b868-3ff5-41aa-b0f1-e230a18f6545';
  $pane->panel = 'middle';
  $pane->type = 'views';
  $pane->subtype = 'os2web_base_panels_view_selfserv';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'override_pager_settings' => 0,
    'use_pager' => 0,
    'nodes_per_page' => '0',
    'pager_id' => '0',
    'offset' => '0',
    'more_link' => 0,
    'feed_icons' => 0,
    'panel_args' => 0,
    'link_to_view' => 0,
    'args' => '',
    'url' => '',
    'display' => 'block_6',
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 3;
  $pane->locks = array();
  $pane->uuid = '65e6b868-3ff5-41aa-b0f1-e230a18f6545';
  $display->content['new-65e6b868-3ff5-41aa-b0f1-e230a18f6545'] = $pane;
  $display->panels['middle'][3] = 'new-65e6b868-3ff5-41aa-b0f1-e230a18f6545';
  $display->hide_title = PANELS_TITLE_NONE;
  $display->title_pane = 'new-f6d5abe9-3d6b-4125-bd0d-baba12924978';
  $mini->display = $display;
  $export['os2web_contact_panel_sidebar'] = $mini;

  return $export;
}
