<?php
/**
 * @file
 * Code for the OS2Web Kontaktblok feature.
 */

include_once 'os2web_contact.features.inc';

/**
 * Helper function to provide a os2web_contact_contact node for views.
 *
 * return int nid of block node.
 */
function os2web_contact_get_block() {
  $result = 0;
  $menu = menu_get_active_trail();
  while ($item = array_pop($menu)) {
    $path = explode('/', $item['link_path']);
    if((isset($path[1]) && $path[1] == 'add') || (isset($path[2]) && $path[2] == 'edit') ) {
      continue;
    }
    if ($path[0] === 'taxonomy' && $path[1] === 'term') {
      $ent = taxonomy_term_load($path[2]);
      $field = field_get_items('taxonomy_term', $ent, 'field_os2web_base_field_contact');
    }
    elseif ($path[0] === 'node') {
      if (isset($path[1]) && is_numeric($path[1])) {
        $ent = node_load($path[1]);
        $field = field_get_items('node', $ent, 'field_os2web_base_field_contact');
      }
    }
    else {
      $node = menu_get_object();
      if ($node) {
        $field = field_get_items('node', $node,'field_os2web_base_field_contact');

        if (empty($field)) {
          // Check if the node is hearings, then user default block from the the settings page.
          if ($node->type == 'os2web_hearings_hearing_case') {
            if ($default_contact_block = variable_get('os2web_hearings_default_contact_block')) {
              $field[0]['nid'] = $default_contact_block['entity_id'];
            }
          }
        }
      }
    }

    if (isset($field[0]['nid'])) {
      $result = $field[0]['nid'];
      break;
    }
  }
  return $result;
}

/**
 * Implements hook_views_post_render().
 */
function os2web_contact_views_post_render(&$view, &$output, &$cache) {
  global $user;

  if ($view->name = 'os2web_contact_view_contact' && $view->human_name === 'Kontaktblok') {
    // Check if the user has the 'editor' role.
    // Add an edit link.
    if (in_array('Editor', $user->roles) && $nid = os2web_contact_get_block()) {
      $output = l(t('Edit'), 'node/' . $nid . '/edit', array(
        'attributes' => array(
          'class' => array('edit-link'),
          'style' => 'position: absolute;top: 20px;right: 0;',
        ),
      )) . $output;
    }
  }
}
/**
 * Implements hook_os2web_help().
 */
function os2web_contact_os2web_help($sections) {

  // Content types.
  $sections['contenttype'] = t('<p><b>Contact block:</b> Add a <a href="@url" target="_blank">contact block</a> that can be used on any page. Contact blocks are blocks that will be shown next to the main content of a page. Add a contact for each department you have on your site. If a contact block is wanted on a specific page, it can be added by editing the page itself.<br />Contact blocks includes opening hours.</p>', array('@url' => url('node/add/os2web-contact-contact')));
  return $sections;
}
