<?php

/**
 * @file
 * OS2web Service Popup
 */

/**
 * Implements hook_FORM_alter().
 */
function os2web_service_popup_form_os2web_settings_settings_form_alter(&$form, &$form_state) {

  $form['os2web_service_popup_config_group'] = array(
    '#type' => 'fieldset',
    '#title' => t('Service Popup'),
  );
  $form['os2web_service_popup_config_group']['os2web_service_popup_min_idle_time'] = array(
    '#type' => 'textfield',
    '#title' => 'Time in miliseconds before the service Popup pops up! default is 5 min. Set to -1 to disable the popup.',
    '#default_value' => variable_get('os2web_service_popup_min_idle_time', 300000),
  );
  $form['os2web_service_popup_config_group']['os2web_service_popup_node_nid'] = array(
    '#type' => 'textfield',
    '#title' => 'The ID of the node to show the body and title field from, on the PopUp',
    '#default_value' => variable_get('os2web_service_popup_node_nid', NULL),
  );
  $form['os2web_service_popup_config_group']['os2web_service_popup_clock_start'] = array(
    '#type' => 'textfield',
    '#title' => 'Time of day, the popup should be enabled. Default is 08:00',
    '#default_value' => variable_get('os2web_service_popup_clock_start', '08:00'),
    '#element_validate' => array('os2web_service_popup_form_validate_field'),
  );
  $form['os2web_service_popup_config_group']['os2web_service_popup_clock_stop'] = array(
    '#type' => 'textfield',
    '#title' => 'Time of day, the popup should be disabled again. Default is 16:00',
    '#default_value' => variable_get('os2web_service_popup_clock_stop', '16:00'),
    '#element_validate' => array('os2web_service_popup_form_validate_field'),
  );
  $form['os2web_service_popup_config_group']['os2web_service_popup_fadein'] = array(
    '#type' => 'textfield',
    '#title' => 'PopUp Fadein time',
    '#default_value' => variable_get('os2web_service_popup_fadein', '300'),
    '#element_validate' => array('element_validate_integer_positive'),
  );
  $form['os2web_service_popup_config_group']['os2web_service_popup_fadeout'] = array(
    '#type' => 'textfield',
    '#title' => 'PopUp Fadeout time',
    '#default_value' => variable_get('os2web_service_popup_fadeout', '300'),
    '#element_validate' => array('element_validate_integer_positive'),
  );
  return $form;
}

/**
 * Generic validate callback for the settings fields.
 */
function os2web_service_popup_form_validate_field($element, &$form_state) {
  switch ($element['#name']) {
    case 'os2web_service_popup_clock_start':
    case 'os2web_service_popup_clock_stop':
      if (!preg_match('/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/', $element['#value'])) {
        form_error($element, t('Your time is in incorrect format. Should be HH:MM.'));
      }
      break;
  }
}

/**
 * Implements hook_preprocess_page().
 */
function os2web_service_popup_preprocess_page(&$vars, $hook) {
  if (user_is_anonymous()) {
    $node = node_load(variable_get('os2web_service_popup_node_nid'));
    $idle_time = variable_get('os2web_service_popup_min_idle_time', 300000);
    $clock_start = variable_get('os2web_service_popup_clock_start', '08:00');
    $clock_stop = variable_get('os2web_service_popup_clock_stop', '16:00');
    $fadein_time = variable_get('os2web_service_popup_fadein', 300);
    $fadeout_time = variable_get('os2web_service_popup_fadeout', 300);

    if ($node && !empty($node->title) && !empty($node->body) && $idle_time > -1 )  {
      // Add settings and javascript to the page. Javascript takes care of the
      // rest.

      $body = isset($node->body[$node->language]) ? $node->body[$node->language][0]['value'] : $node->body['und'][0]['value'];

      drupal_add_js(array('os2web_service_popup' => array(
        'title'     => $node->title,
        'body'      => $body,
        'idle_time' => $idle_time,
        'clock_start' => $clock_start,
        'clock_stop' => $clock_stop,
        'fadein' => $fadein_time,
        'fadeout' => $fadeout_time,
      )), 'setting');

      drupal_add_js(drupal_get_path('module', 'os2web_service_popup') .'/js/os2web_service_popup.js');
      drupal_add_js(drupal_get_path('module', 'os2web_service_popup') .'/js/idle-timer.min.js');

      drupal_add_css(drupal_get_path('module', 'os2web_service_popup') . '/css/os2web_service_popup.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
    }
  }
}
