<?php
/**
 * @file
 * Code for the OS2Web Spotbokse feature.
 */

include_once 'os2web_spotbox.features.inc';

/**
 * Implements hook_os2web_help().
 */
function os2web_spotbox_os2web_help($sections) {

  // Contenttypes.
  $sections['contenttype'] = t('<p><b id=="os2web_spotbox">Spotbox:</b> Create a <a href="@url">Spotbox</a> to quickly add a box of content on one of your pages. Promote a spotbox to a frontpage. In the individually pages, add a reference to the Spotbox you have created, to enable the spotbox on a specific page.</p>', array('@url' => 'add/node/os2web_spotbox_box'));

  return $sections;
}

function os2web_spotbox_get_link_setting($nid) {
  $link = '';
  if (is_numeric($nid)) {
    $node = node_load($nid);
    $field = field_get_items('node', $node, 'field_os2web_spotbox_url_setting');
    if ($field && $field[0]['value']) {
      $link = '_blank';
    }
  }
  print $link;
}

