<?php

/**
 * @file
 * Code for the OS2Web Webform feature.
 */

include_once 'os2web_webform.features.inc';

/**
 * Implements hook_menu().
 */
function os2web_webform_menu() {
  $items['node/%/submission/%/download'] = array(
    'page callback' => 'os2web_webform_download_request_page',
    'page arguments' => array(1, 3),
    'access arguments' => array("access content"),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'title' => 'Download',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function os2web_webform_theme($existing, $type, $theme, $path) {
  return array(
    'confirmation_page' => array(
      'variables' => array(
        'fields' => NULL,
        'node' => NULL,
        'nid' => NULL,
        'files' => NULL,
      ),
      'template' => 'templates/dlrequest',
    ),
  );
}

/**
 * Page callback for submission downloads.
 */
function os2web_webform_download_request_page($nid, $sid) {
  // Get the submission array.
  $submission = webform_menu_submission_load($sid, $nid);

  // Process the submission.
  $data = os2web_webform_process_submission($submission, node_load($nid));

  // Process the data throught the theme layer.
  $output = theme("confirmation_page", $data);

  // TODO: Send the mail.
  /* reg_send_email("confirmation", $data); */

  return $output;
}

/**
 * Function to process a submission.
 */
function os2web_webform_process_submission(&$submission, $node) {
  if ($submission) {
    $fields = array();
    foreach (array_keys($submission->data) as $key) {
      $fields[$key] = array(
        'value' => $submission->data[$key]['value'][0],
        'label' => $node->webform['components'][$key]['name'],
      );
    }

    $attached_files = field_view_field('node', $node, 'field_os2web_webform_attach', array('label' => 'hidden'));
    $data = array(
      'sid' => $submission->sid,
      'nid' => $node->nid,
      'node' => $node,
      'files' => $attached_files,
      'fields' => $fields,
    );

    return $data;
  }
}

/**
 * Implements hook_form_alter().
 */
function os2web_webform_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'webform_configure_form':
      // Deny acces to redirection setup.
      $form['submission']['redirection']['#access'] = FALSE;
      break;
  }
}

/**
 * Implements hook_node_presave().
 */
function os2web_webform_node_presave($node) {
  if (($node->type === 'webform')) {
    $node->webform['redirect_url'] = 'node/%nid/submission/%sid/download';
  }
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Apparently the only way to let drupal search modules for themes.
 * Resource:
 *   http://www.metachunk.com/blog/adding-module-path-drupal-7-theme-registry
 */
function os2web_webform_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'os2web_webform');
  // Munge on a copy.
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _os2web_webform_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter).
 *
 * @param array $array
 *   Altered array
 *
 * @param mixed $element
 *   The element to insert
 */
function _os2web_webform_insert_after_first_element(&$array, $element) {
  if (is_array($array)) {
    $first_element = array_shift($array);
    array_unshift($array, $first_element, $element);
  }
}

/**
 * Implements hook_os2web_help().
 */
function os2web_webform_os2web_help($sections) {

  // Contenttypes.
  $sections['contenttype'] = t('<p><b>Webform:</b> Create a <a href="@url" target="_blank">Webform</a> to be able to give your visitors questionaries. Add multiple types of questions to an Webform, an publish it. After saving the webform, you can setup to recieve an email on every submission  under the tab [Webform] -> [Email], as a bonus you can also send a thank you email to the visitor after it is submitted.<br /> When your visitors submit an reply to your webform, it will be saved to a list under [Result] on the Webform. Additionally you can download the complete list of submissions under the tab [Result] -> [Download]</p>', array('@url' => 'node/add/webform'));

  return $sections;
}
