<?php
/**
 * @file
 * os2web_mobile_extras.module
 *
 * OS2Web mobile module
 * adds custom functionality for mobile access to os2web
 *
 * @category
 * @author   Thomas Thune Hansen <tth@bellcom.dk>
 */

// Load features.
require_once 'os2web_mobile_feature/os2web_mobile_feature.features.inc';

// Load menu_block blocks.
module_load_include('inc', 'os2web_mobile', 'os2web_mobile.menu_blocks');

/**
 * Implements hook_init().
 */
function os2web_mobile_init() {
  // Detect mobile domain and redirect to correct frontpage.
  if (_os2web_mobile_is_mobile() && drupal_is_front_page()) {
    drupal_goto(variable_get('os2web_mobile_mobile_frontpage', 'mobile'));
  }

  drupal_add_js(drupal_get_path('module', 'os2web_mobile') . '/os2web_mobile.js');
  drupal_add_css(drupal_get_path('module', 'os2web_mobile') . '/os2web_mobile.css');
}

/**
 * Implements hook_menu().
 */
function os2web_mobile_menu() {
  $items = array();

  // Frontpage hijack.
  $items['frontpage'] = array(
    'page callback' => '_os2web_mobile_frontpage',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  // Admin menu.
  $items['admin/config/os2web_mobile'] = array(
    'title' => 'OS2Web mobile settings',
    'description' => 'General settings ',
    'position' => 'right',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/config/os2web_mobile/settings'] = array(
    'title' => 'OS2Web mobile settings',
    'description' => 'Change settings for OS2web mobile',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2web_mobile_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'os2web_mobile.admin.inc',
  );

  return $items;
}
/**
 * Implements hook_custom_theme().
 */
function os2web_mobile_custom_theme() {
  // Check if the page requested is mobile, if it is
  // we serve the mobile theme.
  if (_os2web_mobile_is_mobile()) {
    return 'os2web_mobile_theme';
  }
}

/**
 * Function to check if the page is requested as mobile.
 */
function _os2web_mobile_is_mobile() {
  if ($_SERVER['HTTP_HOST'] === variable_get('os2web_mobile_domain', NULL)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function os2web_mobile_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}
