<?php
/**
 * @file
 * Code for the OS2Web Selvbetjeningslinks feature.
 */

include_once 'os2web_selfservicelinks.features.inc';

/**
 * Implements hook_os2web_help().
 */
function os2web_selfservicelinks_os2web_help($sections) {

  // Importers.
  $sections['import'] = t('<p><b id=="os2web_selfservicelinks">Selfservice Links:</b> Initialize the importer for Selfservice Links at <a href="@url">the import page.</a></p>', array('@url' => 'import/os2web_selfservicelinks_feeds_import'));

  return $sections;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function os2web_selfservicelinks_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'feeds_tamper' && $plugin_type == 'plugins') {
    return 'plugins';
  }
}

/**
 * Find term id from string with kle number.
 */
function os2web_selfservicelinks_find_term($string, $vid) {
  if (preg_match('/(\d+\.\d+\.\d+)/', $string, $match)) {
    $kle = $match[0];

    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'taxonomy_term')
      ->propertyCondition('vid', $vid)
      ->propertyCondition('name', '%' . $kle . '%', 'LIKE');
    $result = $query->execute();

    if (!empty($result['taxonomy_term'])) {
      return key($result['taxonomy_term']);
    }
  }
  return '';
}
